# Generated by Django 4.1.5 on 2023-01-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("zip", models.CharField(max_length=120)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("athletes_present", models.IntegerField()),
                ("athletes_needed", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("message", models.TextField()),
            ],
        ),
    ]
